import { useState } from "react";
import { Link } from "react-router-dom";
import {
  ArrowRight,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Gift,
  Headphones,
  KeyRound,
  Lock,
  MessageCircle,
  Mic2,
  PartyPopper,
  ShieldCheck,
  Shirt,
  Sparkles,
  Star,
  Ticket,
  Users,
  X,
} from "lucide-react";
import Layout from "@/components/layout/Layout";
import { cn } from "@/lib/utils";

const heroImage = "https://cdn.builder.io/api/v1/image/assets%2F387c17f062d04bd5837dfeec0d29ae1e%2Fc9adf9eed6084a7aa679bda15a5ade11?format=webp&width=800&height=1200";
const cities = [
  ["Los Angeles", "USA", "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?q=80&w=800&auto=format&fit=crop"],
  ["New York", "USA", "https://images.unsplash.com/photo-1496588152823-86ff7695e68f?q=80&w=800&auto=format&fit=crop"],
  ["London", "UK", "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop"],
  ["Paris", "France", "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop"],
  ["Dubai", "UAE", "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=800&auto=format&fit=crop"],
  ["Tokyo", "Japan", "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?q=80&w=800&auto=format&fit=crop"],
];
const gallery = [
  ["Previous Meet & Greets", "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=900&auto=format&fit=crop", false],
  ["Live Concerts", "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=900&auto=format&fit=crop", false],
  ["Fan Photos", "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=900&auto=format&fit=crop", true],
  ["Signed Merchandise", "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=900&auto=format&fit=crop", false],
  ["VIP Dinners", "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=900&auto=format&fit=crop", true],
];
const perks = [
  [Camera, "Professional Photos", "Capture the moment with an official photo."],
  [MessageCircle, "One-on-One Conversation", "A personal moment to remember forever."],
  [Shirt, "Signed Merchandise", "Take home a special signed keepsake."],
  [PartyPopper, "VIP Lounge Access", "Relax in an exclusive pre-event lounge."],
  [Gift, "Exclusive Gifts", "Receive a curated Bailey gift bag."],
  [Ticket, "Priority Entry", "Enjoy a seamless, first-class arrival."],
];
const reviews = [
  ["The entire experience felt so thoughtful and personal. It was a dream come true.", "Jessica M.", "Gold VIP Member", "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop"],
  ["Meeting Bailey in person was unforgettable. Every detail felt beautifully curated.", "David R.", "Platinum VIP Member", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop"],
  ["The photos, lounge, and gift were incredible. I cannot wait for the next event.", "Sophia K.", "Gold VIP Member", "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=200&auto=format&fit=crop"],
];

export default function MeetGreet() {
  const [showAccess, setShowAccess] = useState(false);
  return <Layout><Hero onAccess={() => setShowAccess(true)} /><WhatIsMeetGreet /><Locations onAccess={() => setShowAccess(true)} /><Gallery /><Testimonials /><LockedSection onAccess={() => setShowAccess(true)} /><Faq /><FinalCta onAccess={() => setShowAccess(true)} />{showAccess && <AccessModal close={() => setShowAccess(false)} />}</Layout>;
}

function Hero({ onAccess }: { onAccess: () => void }) {
  return <section className="relative overflow-hidden border-b border-border bg-noise py-14 sm:py-20"><div className="pointer-events-none absolute -left-20 top-0 h-96 w-96 rounded-full bg-gold/10 blur-[120px]" /><div className="container relative grid items-center gap-10 lg:grid-cols-[1fr_0.9fr]"><div className="text-center lg:text-left"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">Exclusive Experiences</p><h1 className="mt-3 font-display text-5xl font-bold uppercase leading-[0.95] text-white sm:text-7xl">Meet Bailey<br /><span className="text-gradient-gold">In Person</span></h1><p className="mt-5 max-w-lg text-sm leading-relaxed text-muted-foreground lg:mx-0 mx-auto">Exclusive Meet &amp; Greet experiences reserved for official VIP Members. Create a memory that stays with you forever.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row lg:justify-start"><Link to="/vip-membership" className="flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-gold-light to-gold px-7 py-3.5 text-xs font-bold uppercase tracking-wider text-black transition-transform hover:scale-105">Become a VIP <CrownIcon /></Link><Link to="/login" className="flex items-center justify-center gap-2 rounded-full border border-gold/60 px-7 py-3.5 text-xs font-bold uppercase tracking-wider text-gold hover:bg-gold/10">Member Login</Link></div><div className="mt-8 flex items-center justify-center gap-2 text-xs text-muted-foreground lg:justify-start"><Lock className="h-4 w-4 text-gold" /> Full details unlock with VIP access</div></div><div className="relative mx-auto w-full max-w-md"><div className="relative overflow-hidden rounded-2xl border border-gold/30 shadow-2xl"><img src={heroImage} alt="Bailey" className="aspect-[0.9/1] w-full object-cover object-top" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-black/10" /></div><div className="absolute -bottom-8 -right-4 w-64 rotate-[-5deg] overflow-hidden rounded-xl border border-gold/60 shadow-[0_0_45px_-8px_hsl(var(--gold)/0.65)] sm:-right-12"><img src="https://cdn.builder.io/api/v1/image/assets%2F387c17f062d04bd5837dfeec0d29ae1e%2F04dbbb8300b149b6b41cd6ca09b9bc7a?format=webp&width=800&height=1200" alt="Bailey VIP membership card" className="aspect-[1.62/1] w-full object-cover" /></div><div className="pointer-events-none absolute -bottom-10 left-1/2 h-10 w-[90%] -translate-x-1/2 rounded-[50%] border border-gold/60 shadow-[0_0_45px_10px_hsl(var(--gold)/0.25)]" /></div></div></section>;
}
function CrownIcon() { return <Sparkles className="h-4 w-4" />; }

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">{eyebrow}</p><h2 className="mt-2 font-display text-3xl font-bold text-white sm:text-4xl">{title}</h2>{copy && <p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">{copy}</p>}</div>; }

function WhatIsMeetGreet() { return <section className="container py-14 sm:py-20"><SectionHeading eyebrow="What Is Meet & Greet?" title="A closer connection to Bailey" copy="VIP Members receive a rare opportunity to step beyond the stage and share an unforgettable moment with Bailey and the community." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{perks.map(([Icon, title, copy]) => <div key={title as string} className="group rounded-xl border border-border bg-card/40 p-4 text-center transition-all hover:-translate-y-1 hover:border-gold/50 hover:shadow-[0_0_30px_-12px_hsl(var(--gold)/0.5)]"><Icon className="mx-auto h-6 w-6 text-gold" /><h3 className="mt-3 text-xs font-semibold text-white">{title as string}</h3><p className="mt-2 text-[10px] leading-relaxed text-muted-foreground">{copy as string}</p><span className="mt-3 inline-block rounded-full bg-gold/10 px-2 py-1 text-[8px] font-bold uppercase tracking-wider text-gold">VIP members only</span></div>)}</div></section>; }

function Locations({ onAccess }: { onAccess: () => void }) { return <section className="container py-12 sm:py-16"><div className="flex items-end justify-between"><SectionHeading eyebrow="Upcoming Locations" title="The experience travels with you" copy="Explore the cities where exclusive moments are waiting. Event details are reserved for official members." /><span className="mb-8 hidden items-center gap-1 text-[10px] uppercase tracking-wider text-gold sm:flex"><Lock className="h-3 w-3" /> Login to view details</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{cities.map(([city, country, image]) => <button key={city} onClick={onAccess} className="group relative overflow-hidden rounded-xl border border-border text-left transition-all hover:-translate-y-1 hover:border-gold/60"><img src={image} alt={city} className="aspect-[0.8/1] w-full object-cover opacity-75 transition-transform duration-500 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent" /><div className="absolute left-3 top-3"><p className="text-sm font-semibold uppercase text-white">{city}</p><p className="text-[10px] text-gold">{country}</p></div><div className="absolute bottom-3 left-3 right-3"><p className="text-[9px] uppercase tracking-wider text-gold-light">Exclusive Event</p><p className="mt-2 flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-white"><Lock className="h-3 w-3 text-gold" /> Login to View Details</p></div></button>)}</div></section>; }

function Gallery() { return <section className="container py-12 sm:py-16"><div className="flex items-end justify-between"><SectionHeading eyebrow="Meet & Greet Gallery" title="Moments worth remembering" /><span className="mb-8 flex items-center gap-1 text-[10px] uppercase tracking-wider text-gold"><Lock className="h-3 w-3" /> More exclusive photos for VIP members</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{gallery.map(([title, image, locked], i) => <div key={title as string} className={cn("group relative overflow-hidden rounded-xl border border-border", i === 0 && "sm:col-span-2") }><img src={image as string} alt={title as string} className={cn("h-full min-h-40 w-full object-cover transition-transform duration-500 group-hover:scale-105", locked && "blur-[2px]")} /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />{locked && <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/35 text-center"><Lock className="h-6 w-6 text-gold" /><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-white">Exclusive Content</p><p className="mt-1 text-[9px] text-gold">VIP Members Only</p></div>}<p className="absolute bottom-3 left-3 text-[10px] font-semibold uppercase tracking-wider text-white">{title as string}</p></div>)}</div></section>; }

function Testimonials() { const [index, setIndex] = useState(0); const review = reviews[index]; return <section className="container py-12 sm:py-16"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading eyebrow="What Fans Say" title="Real experiences. Real emotion." copy="Our VIP community is at the heart of every Meet & Greet." /><div className="rounded-2xl border border-border bg-card/50 p-6"><div className="flex gap-1 text-gold">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="h-4 w-4 fill-gold" />)}</div><p className="mt-5 text-sm italic leading-relaxed text-muted-foreground">“{review[0]}”</p><div className="mt-6 flex items-center justify-between"><div className="flex items-center gap-3"><img src={review[3]} alt={review[1]} className="h-10 w-10 rounded-full object-cover" /><div><p className="text-sm font-semibold text-white">{review[1]}</p><p className="text-xs text-gold">{review[2]}</p></div></div><div className="flex gap-2"><button aria-label="Previous review" onClick={() => setIndex((index - 1 + reviews.length) % reviews.length)} className="rounded-full border border-border p-2 text-muted-foreground hover:border-gold hover:text-gold"><ChevronLeft className="h-4 w-4" /></button><button aria-label="Next review" onClick={() => setIndex((index + 1) % reviews.length)} className="rounded-full border border-border p-2 text-muted-foreground hover:border-gold hover:text-gold"><ChevronRight className="h-4 w-4" /></button></div></div></div></div></section>; }

function LockedSection({ onAccess }: { onAccess: () => void }) { return <section className="container py-12 sm:py-16"><div className="relative overflow-hidden rounded-2xl border border-gold/40 p-8 text-center sm:p-16"><div className="absolute inset-0 scale-110 bg-[url('https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=1600&auto=format&fit=crop')] bg-cover bg-center blur-md" /><div className="absolute inset-0 bg-black/80" /><div className="relative"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-gold bg-gold/10 text-gold shadow-[0_0_35px_hsl(var(--gold)/0.35)]"><Lock className="h-7 w-7" /></span><h2 className="mt-6 font-display text-3xl font-bold text-white sm:text-4xl">VIP Members Only</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">Unlock complete event schedules, venue information, reservation access, exclusive galleries, and private Meet &amp; Greet experiences by becoming an official VIP Member.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/vip-membership" className="flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-gold-light to-gold px-7 py-3.5 text-xs font-bold uppercase tracking-wider text-black">Join VIP Membership <ArrowRight className="h-4 w-4" /></Link><button onClick={onAccess} className="flex items-center justify-center gap-2 rounded-full border border-gold/60 px-7 py-3.5 text-xs font-bold uppercase tracking-wider text-gold hover:bg-gold/10">Member Login</button></div></div></div></section>; }

function Faq() { const [open, setOpen] = useState<number | null>(0); const items = ["How do I become eligible?", "Do I need VIP Membership?", "Can I bring a guest?", "Are children allowed?", "Will I receive professional photos?", "Can I upgrade my experience?"]; return <section className="container py-12 sm:py-16"><div className="mx-auto max-w-3xl"><SectionHeading eyebrow="Frequently Asked Questions" title="Meet & Greet details" />{items.map((item, i) => <div key={item} className="border-b border-border"><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between py-4 text-left text-sm text-white"><span>{item}</span><ChevronDown className={cn("h-4 w-4 text-gold transition-transform", open === i && "rotate-180")} /></button><div className={cn("grid transition-[grid-template-rows] duration-300", open === i ? "grid-rows-[1fr]" : "grid-rows-[0fr]")}><p className="overflow-hidden text-xs leading-relaxed text-muted-foreground">Meet &amp; Greet access is reserved for official VIP Members. Exact event details and guest policies are shared securely after membership access is confirmed.</p></div></div>)}</div></section>; }

function FinalCta({ onAccess }: { onAccess: () => void }) { return <section className="container pb-20 pt-8 sm:pb-28"><div className="relative overflow-hidden rounded-2xl border border-gold/40 bg-gradient-to-r from-gold/15 via-card to-gold/10 p-8 text-center sm:p-14"><Headphones className="absolute left-8 top-8 h-10 w-10 text-gold/20" /><Mic2 className="absolute bottom-8 right-8 h-10 w-10 text-gold/20" /><h2 className="font-display text-3xl font-bold text-white sm:text-4xl">Your Chance to Meet Bailey Starts Here</h2><p className="mx-auto mt-3 max-w-xl text-sm text-muted-foreground">Become an official VIP Member to unlock exclusive Meet &amp; Greet experiences around the world.</p><Link to="/vip-membership" onClick={onAccess} className="mt-7 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-gold-light to-gold px-8 py-4 text-xs font-bold uppercase tracking-wider text-black transition-transform hover:scale-105">Become a VIP Member <ArrowRight className="h-4 w-4" /></Link></div></section>; }

function AccessModal({ close }: { close: () => void }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/80 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="access-title"><div className="relative w-full max-w-md rounded-2xl border border-gold/50 bg-card p-7 text-center shadow-[0_0_70px_-15px_hsl(var(--gold)/0.5)]"><button onClick={close} aria-label="Close access dialog" className="absolute right-4 top-4 rounded-full p-2 text-muted-foreground hover:text-white"><X className="h-5 w-5" /></button><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-gold bg-gold/10 text-gold"><ShieldCheck className="h-6 w-6" /></span><h2 id="access-title" className="mt-5 font-display text-2xl font-bold text-white">VIP Access Required</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">This experience is exclusively available to official VIP Members.<br /><br />Please join the VIP Membership or log in to your VIP account to continue.</p><div className="mt-7 flex flex-col gap-3"><Link to="/vip-membership" onClick={close} className="rounded-full bg-gradient-to-r from-gold-light to-gold px-6 py-3 text-xs font-bold uppercase tracking-wider text-black">Join VIP Membership</Link><Link to="/login" onClick={close} className="rounded-full border border-gold/60 px-6 py-3 text-xs font-bold uppercase tracking-wider text-gold hover:bg-gold/10">Member Login</Link></div></div></div>; }
