import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, CalendarDays, Check, Crown, Gem, KeyRound, LogOut, MessageCircle, Newspaper, Package, QrCode, ShieldCheck, Sparkles, Ticket } from "lucide-react";
import Layout from "@/components/layout/Layout";
import { clearVipSession, getLoggedInMember, VipMember } from "@/lib/vip-auth";

const cardImage = "https://cdn.builder.io/api/v1/image/assets%2F387c17f062d04bd5837dfeec0d29ae1e%2F04dbbb8300b149b6b41cd6ca09b9bc7a?format=webp&width=800&height=1200";

export default function MemberDashboard() {
  const navigate = useNavigate();
  const [member, setMember] = useState<VipMember>();
  useEffect(() => {
    const sessionMember = getLoggedInMember();
    if (!sessionMember) {
      navigate("/login", { replace: true });
      return;
    }
    setMember(sessionMember);
  }, [navigate]);

  if (!member) return null;
  const logout = () => {
    clearVipSession();
    navigate("/login", { replace: true });
  };

  return <Layout><main className="container py-12 sm:py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">Private Member Area</p><h1 className="mt-2 font-display text-4xl font-bold text-white sm:text-5xl">Welcome back, {member.name}</h1><p className="mt-3 text-sm text-muted-foreground">Your official Bailey VIP access, all in one place.</p></div><button onClick={logout} className="flex items-center gap-2 self-start rounded-full border border-border px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-muted-foreground transition-colors hover:border-gold hover:text-gold sm:self-auto"><LogOut className="h-4 w-4" /> Logout</button></div><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><MemberSummary member={member} /><DigitalCard member={member} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><DashboardLink icon={Ticket} title="Meet & Greet Access" copy="Explore your exclusive event privileges." to="/meet-greet" /><DashboardLink icon={Newspaper} title="VIP News" copy="Read the latest official updates." to="/news" /><DashboardLink icon={MessageCircle} title="Contact Management" copy="Get help from the official team." to="/contact" /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><StatusPanel /><ProfilePanel member={member} /></div></main></Layout>;
}

function MemberSummary({ member }: { member: VipMember }) { return <section className="rounded-2xl border border-gold/30 bg-card/60 p-6 shadow-[0_0_40px_-16px_hsl(var(--gold)/0.4)]"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-gold/15 text-gold"><Crown className="h-5 w-5" /></span><div><p className="text-xs text-muted-foreground">Membership Plan</p><h2 className="font-display text-2xl text-white">{member.plan}</h2></div></div><div className="mt-8 grid grid-cols-2 gap-4"><div className="rounded-xl border border-border bg-background/60 p-4"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Member ID</p><p className="mt-2 font-mono text-sm text-gold">{member.memberId}</p></div><div className="rounded-xl border border-border bg-background/60 p-4"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Status</p><p className="mt-2 flex items-center gap-1 text-sm text-gold"><span className="h-2 w-2 rounded-full bg-gold" />{member.status}</p></div></div><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-gold" /> Verified official VIP member</div></section>; }

function DigitalCard({ member }: { member: VipMember }) { return <section className="relative overflow-hidden rounded-2xl border border-border bg-card/50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-gold">Digital VIP Card</p><h2 className="mt-1 font-display text-xl text-white">Your official access pass</h2></div><QrCode className="h-8 w-8 text-gold" /></div><div className="mt-5 grid gap-5 sm:grid-cols-[1.2fr_0.8fr] sm:items-center"><img src={cardImage} alt="Digital Bailey VIP card" className="aspect-[1.62/1] w-full rounded-xl object-cover shadow-2xl" /><div className="space-y-3 text-xs"><p className="flex justify-between border-b border-border pb-2 text-muted-foreground"><span>Name</span><strong className="text-white">{member.name}</strong></p><p className="flex justify-between border-b border-border pb-2 text-muted-foreground"><span>Level</span><strong className="text-gold">{member.plan}</strong></p><p className="flex justify-between text-muted-foreground"><span>Access</span><strong className="text-white">All VIP Content</strong></p></div></div></section>; }

function DashboardLink({ icon: Icon, title, copy, to }: { icon: typeof Ticket; title: string; copy: string; to: string }) { return <Link to={to} className="group rounded-xl border border-border bg-card/40 p-5 transition-all hover:-translate-y-1 hover:border-gold/50 hover:shadow-[0_0_30px_-12px_hsl(var(--gold)/0.5)]"><Icon className="h-6 w-6 text-gold" /><h3 className="mt-4 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{copy}</p><ArrowRight className="mt-4 h-4 w-4 text-gold transition-transform group-hover:translate-x-1" /></Link>; }

function StatusPanel() { const steps = ["Application Submitted", "Membership Approved", "Payment Confirmed", "VIP Card In Production", "Packaged", "Shipped"]; return <section className="rounded-2xl border border-border bg-card/50 p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-gold">Live Status</p><h2 className="mt-1 font-display text-2xl text-white">Membership package</h2></div><span className="rounded-full bg-gold/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-gold">In Production</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{steps.map((step, i) => <div key={step} className="flex items-center gap-3"><span className={i < 3 ? "flex h-6 w-6 items-center justify-center rounded-full bg-gold text-black" : i === 3 ? "flex h-6 w-6 items-center justify-center rounded-full border border-gold text-gold animate-pulse" : "flex h-6 w-6 items-center justify-center rounded-full border border-border text-muted-foreground"}>{i < 3 ? <Check className="h-3.5 w-3.5" /> : i === 3 ? "•" : ""}</span><span className={i <= 3 ? "text-xs text-white" : "text-xs text-muted-foreground"}>{step}</span></div>)}</div></section>; }

function ProfilePanel({ member }: { member: VipMember }) { return <section className="rounded-2xl border border-border bg-card/50 p-6"><p className="text-xs uppercase tracking-[0.25em] text-gold">Profile</p><h2 className="mt-1 font-display text-2xl text-white">Package details</h2><div className="mt-6 space-y-4 text-xs"><p className="flex items-center gap-3 text-muted-foreground"><CalendarDays className="h-4 w-4 text-gold" /> Estimated delivery <strong className="ml-auto text-white">August 21, 2026</strong></p><p className="flex items-center gap-3 text-muted-foreground"><Package className="h-4 w-4 text-gold" /> Package contents <strong className="ml-auto text-white">6 items</strong></p><p className="flex items-center gap-3 text-muted-foreground"><Gem className="h-4 w-4 text-gold" /> Member level <strong className="ml-auto text-gold">{member.plan}</strong></p><p className="flex items-center gap-3 text-muted-foreground"><KeyRound className="h-4 w-4 text-gold" /> Account access <strong className="ml-auto text-white">Active</strong></p></div></section>; }
