import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, CalendarDays, ChevronDown, Facebook, Instagram, Music2, Play, Sparkles, Star, Ticket, Twitter, Users, Youtube } from "lucide-react";
import Layout from "@/components/layout/Layout";
import { cn } from "@/lib/utils";

const stories = [
  { category: "Music", date: "May 20, 2024", title: "New Music Coming Soon", summary: "Zona is back in the studio and working on something special for you all.", image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=900&auto=format&fit=crop" },
  { category: "Community", date: "May 15, 2024", title: "Thank You, ZM Nation", summary: "A huge thank you to all the amazing fans who continue to support the journey.", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=900&auto=format&fit=crop" },
  { category: "Behind the Scenes", date: "May 10, 2024", title: "Behind the Scenes", summary: "A look into the making of Zona's latest projects and upcoming events.", image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=900&auto=format&fit=crop" },
  { category: "VIP", date: "May 05, 2024", title: "VIP Experiences", summary: "Exclusive Meet & Greets, events, and more for official VIP members.", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?q=80&w=900&auto=format&fit=crop" },
  { category: "Events", date: "April 28, 2024", title: "The Summer Event Calendar", summary: "Discover what is coming next for our global fan community.", image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?q=80&w=900&auto=format&fit=crop" },
  { category: "Meet & Greet", date: "April 20, 2024", title: "A Night to Remember", summary: "Reliving the most unforgettable moments from our latest fan experience.", image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=900&auto=format&fit=crop" },
  { category: "Announcements", date: "April 14, 2024", title: "Welcome to the New ZM Portal", summary: "Your official destination for updates, access, and community news.", image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=900&auto=format&fit=crop" },
  { category: "VIP", date: "April 08, 2024", title: "The Gold Tier Has Arrived", summary: "Explore the newest benefits created for our most dedicated members.", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=900&auto=format&fit=crop" },
  { category: "Music", date: "March 30, 2024", title: "Inside the Creative Process", summary: "A glimpse at the people and ideas shaping the next chapter.", image: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?q=80&w=900&auto=format&fit=crop" },
];
const categories = ["All", "Music", "VIP", "Events", "Meet & Greet", "Announcements", "Behind the Scenes", "Community"];
const announcements = [
  ["New Album Coming Soon", "Music", Music2],
  ["Upcoming Meet & Greet Locations", "Events", Ticket],
  ["Exclusive VIP Merchandise Launch", "VIP", Sparkles],
];

export default function News() {
  const [category, setCategory] = useState("All");
  const filtered = useMemo(() => category === "All" ? stories : stories.filter((story) => story.category === category), [category]);
  return <Layout><Hero /><Featured /><section className="container py-12 sm:py-16"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">The Newsroom</p><h2 className="mt-2 font-display text-3xl font-bold text-white sm:text-4xl">Latest Updates</h2></div><div className="flex max-w-full gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={cn("whitespace-nowrap rounded-full border px-4 py-2 text-[10px] font-semibold uppercase tracking-wider transition-all", category === item ? "border-gold bg-gold/15 text-gold shadow-[0_0_20px_-8px_hsl(var(--gold)/0.8)]" : "border-border text-muted-foreground hover:border-gold/50 hover:text-gold")}>{item}</button>)}</div></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((story) => <NewsCard key={story.title} story={story} />)}</div></section><Announcements /><Social /><Newsletter /><FooterNote /></Layout>;
}

function Hero() { return <section className="relative overflow-hidden border-b border-border bg-noise py-16 text-center sm:py-24"><div className="pointer-events-none absolute left-1/2 top-0 h-72 w-[700px] -translate-x-1/2 rounded-full bg-gold/10 blur-[120px]" /><div className="relative"><p className="text-xs font-semibold uppercase tracking-[0.35em] text-gold">News</p><h1 className="mt-3 font-display text-5xl font-bold uppercase text-white sm:text-7xl">The Latest From <span className="text-gradient-gold">Zona</span></h1><p className="mx-auto mt-4 max-w-xl text-sm text-muted-foreground">Stay informed with the latest announcements, exclusive updates, upcoming events, and official news from Zona Mae.</p><div className="mx-auto mt-6 flex items-center justify-center gap-3 text-gold"><span className="h-px w-14 bg-gold/50" /><Star className="h-4 w-4 fill-gold" /><span className="h-px w-14 bg-gold/50" /></div></div></section>; }

function Featured() { const story = stories[0]; return <section className="container py-12 sm:py-16"><div className="group grid overflow-hidden rounded-2xl border border-gold/30 bg-card/50 transition-all hover:border-gold/60 hover:shadow-[0_0_50px_-16px_hsl(var(--gold)/0.55)] lg:grid-cols-[1.2fr_1fr]"><div className="relative overflow-hidden"><img src={story.image} alt={story.title} className="aspect-[1.4/1] h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent lg:bg-gradient-to-r" /><span className="absolute left-5 top-5 rounded-full bg-gold px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-black">Featured Story</span></div><div className="flex flex-col justify-center p-7 sm:p-10"><div className="flex items-center gap-3 text-[10px] uppercase tracking-wider text-gold"><span>{story.category}</span><span className="h-1 w-1 rounded-full bg-gold" /><span>{story.date}</span></div><h2 className="mt-4 font-display text-3xl font-bold text-white sm:text-4xl">{story.title}</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{story.summary} Stay close for the official announcement and everything coming next.</p><button className="mt-7 flex w-fit items-center gap-2 rounded-full bg-gradient-to-r from-gold-light to-gold px-6 py-3 text-xs font-bold uppercase tracking-wider text-black transition-transform hover:scale-105">Read Full Story <ArrowRight className="h-4 w-4" /></button></div></div></section>; }

function NewsCard({ story }: { story: typeof stories[number] }) { return <article className="group overflow-hidden rounded-xl border border-border bg-card/40 transition-all duration-300 hover:-translate-y-1 hover:border-gold/50 hover:shadow-[0_0_35px_-14px_hsl(var(--gold)/0.6)]"><div className="relative overflow-hidden"><img src={story.image} alt={story.title} className="aspect-[1.55/1] w-full object-cover transition-transform duration-500 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" /><span className="absolute left-3 top-3 rounded-full bg-background/85 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider text-gold">{story.category}</span></div><div className="p-5"><div className="flex items-center gap-1 text-[10px] uppercase tracking-wider text-muted-foreground"><CalendarDays className="h-3 w-3 text-gold" />{story.date}</div><h3 className="mt-3 font-display text-xl text-white">{story.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-muted-foreground">{story.summary}</p><button className="mt-5 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-gold transition-colors hover:text-gold-light">Read More <ArrowRight className="h-3 w-3" /></button></div></article>; }

function Announcements() { return <section className="container py-12 sm:py-16"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">Save the Date</p><h2 className="mt-2 font-display text-3xl font-bold text-white sm:text-4xl">Upcoming Announcements</h2></div><Sparkles className="mb-2 h-6 w-6 text-gold" /></div><div className="mt-8 grid gap-4 md:grid-cols-3">{announcements.map(([title, category, Icon]) => <div key={title as string} className="group rounded-xl border border-border bg-card/40 p-5 transition-all hover:border-gold/50 hover:bg-gold/5"><div className="flex items-start justify-between"><Icon className="h-7 w-7 text-gold" /><span className="rounded-full bg-gold/10 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-gold">Coming Soon</span></div><p className="mt-7 text-[10px] uppercase tracking-wider text-muted-foreground">{category as string}</p><h3 className="mt-1 font-display text-xl text-white">{title as string}</h3><div className="mt-5 h-px w-full bg-gradient-to-r from-gold/50 to-transparent" /></div>)}</div></section>; }

function Social() { const socials = [[Instagram, "Instagram", "Daily moments & stories"], [Music2, "TikTok", "Join the conversation"], [Youtube, "YouTube", "Watch the latest videos"], [Facebook, "Facebook", "Connect with ZM Nation"], [Twitter, "X / Twitter", "Official announcements"]]; return <section className="container py-10 sm:py-14"><div className="rounded-2xl border border-border bg-card/30 p-6 sm:p-8"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">Follow Along</p><h2 className="mt-2 font-display text-2xl font-bold text-white sm:text-3xl">Stay in the Zona Mae world</h2></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{socials.map(([Icon, title, copy]) => <a key={title as string} href="https://instagram.com" target="_blank" rel="noreferrer" className="group rounded-xl border border-border p-4 transition-all hover:-translate-y-1 hover:border-gold/50"><Icon className="h-5 w-5 text-gold transition-transform group-hover:scale-110" /><h3 className="mt-4 text-xs font-semibold text-white">{title as string}</h3><p className="mt-1 text-[10px] text-muted-foreground">{copy as string}</p></a>)}</div></div></section>; }

function Newsletter() { return <section className="container py-10"><div className="flex flex-col items-center justify-between gap-6 rounded-2xl border border-border bg-card/50 p-7 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Stay Connected</p><p className="mt-2 text-sm text-muted-foreground">Get the latest updates, news, and exclusive content straight to your inbox.</p></div><form onSubmit={(e) => e.preventDefault()} className="flex w-full max-w-md gap-2 sm:w-auto"><input type="email" required placeholder="Enter your email" className="min-w-0 flex-1 rounded-full border border-border bg-background px-4 py-3 text-xs text-white outline-none focus:border-gold" /><button className="rounded-full bg-gradient-to-r from-gold-light to-gold px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-black">Subscribe</button></form></div></section>; }
function FooterNote() { return <div className="container pb-12 text-center text-xs text-muted-foreground"><p>© 2026 Zona Mae Official Fan Access. All Rights Reserved.</p></div>; }
